services:

  shootime.module:
    class: Shootime
    public: true
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'shootime'

  shootime.context:
    class: Context
    public: true
    factory: [ 'Context', 'getContext' ]

  #####################
  # PS Account
  shootime.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    public: true
    arguments:
      - "5.0"

  shootime.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    public: true
    arguments:
      - "@shootime.ps_accounts_installer"

  #####################
  # PS Billing
  shootime.ps_billings_context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    public: true
    arguments:
      - '@shootime.ps_accounts_facade'
      - '@shootime.context'

  shootime.ps_billings_facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
      - '@shootime.ps_billings_context_wrapper'
      - '@shootime.module'

  # Remove this if you don't need BillingService
  shootime.ps_billings_service:
    class: PrestaShopCorp\Billing\Services\BillingService
    public: true
    arguments:
      - '@shootime.ps_billings_context_wrapper'
      - '@shootime.module'
